kind: pipeline
name: default

steps:
  - name: build
    image: python:3.5
    commands:
      - apt-get install python3-sip-dev
      - apt-get install python3-pyqt5
      - python setup.py install
#      - pip install pylint
#      - pylint plover_vcs
      - python -m unittest discover
