kind: pipeline
name: default

steps:
  - name: build
    image: python:3.5
    commands:
      - pip install PyQt5-sip
      - python setup.py install
#      - pip install pylint
#      - pylint plover_vcs
      - python -m unittest discover
